### ISSUE TITLE
Storage menu crash on Android 10

### ISSUE THREAD

**Issue by arminn** [xen-troops/meta-xt-prod-devel#271]
Settings crash when accessing "storage" menu in Android 10 

06-15 11:53:41.505  3720  3720 D AndroidRuntime: Shutting down VM
06-15 11:53:41.506  3720  3720 E AndroidRuntime: FATAL EXCEPTION: main
06-15 11:53:41.506  3720  3720 E AndroidRuntime: Process: com.android.car.settings, PID: 3720
06-15 11:53:41.506  3720  3720 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.settingslib.applications.StorageStatsSource$ExternalStorageStats com.android.car.settings.storage.StorageAsyncLoader$AppsStorageResult.getExternalStats()' on a null object reference
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settings.storage.StorageMediaCategoryPreferenceController.calculateCategoryUsage(StorageMediaCategoryPreferenceController.java:47)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settings.storage.StorageUsageBasePreferenceController.onDataLoaded(StorageUsageBasePreferenceController.java:73)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settings.storage.StorageSettingsManager.onReceivedSizes(StorageSettingsManager.java:100)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settings.storage.StorageSettingsManager.access$500(StorageSettingsManager.java:43)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settings.storage.StorageSettingsManager$VolumeSizeCallback.onLoadFinished(StorageSettingsManager.java:127)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settings.storage.StorageSettingsManager$VolumeSizeCallback.onLoadFinished(StorageSettingsManager.java:109)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:254)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:188)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:173)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.content.Loader.deliverResult(Loader.java:131)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.car.settingslib.loader.AsyncLoader.deliverResult(AsyncLoader.java:65)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:238)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:78)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:275)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at androidx.loader.content.ModernAsyncTask$3.run(ModernAsyncTask.java:143)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-15 11:53:41.506  3720  3720 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
06-15 11:53:34.028  1489  1527 I chatty  : uid=1000(system) android.io identical 3 lines
06-15 11:53:34.035  1489  1527 I DropBoxManagerService: add tag=system_app_strictmode isTagEnabled=true flags=0x2
06-15 11:53:41.511  1489  1511 W ActivityTaskManager:   Force finishing activity com.android.car.settings/.Settings
06-15 11:53:41.512  1489  3786 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2

**Comment by arminn** [comment]
not actual
